import { prisma } from "@/lib/db/prisma";
import type { AIAnalysis, Prisma } from "@prisma/client";

/** Repository layer for AI analysis and request records. */
export class AiRepository {
  /** Stores a completed profile analysis. */
  static async createAnalysis(data: Prisma.AIAnalysisUncheckedCreateInput): Promise<AIAnalysis> {
    return prisma.aIAnalysis.create({ data });
  }

  /** Updates the profile score generated by the latest analysis. */
  static async updateProfileScore(profileId: string, score: number): Promise<void> {
    await prisma.profile.update({ where: { id: profileId }, data: { profileScore: score } });
  }

  /** Lists the authenticated user's saved analyses, newest first. */
  static async findAnalyses(profileId: string, limit: number): Promise<AIAnalysis[]> {
    return prisma.aIAnalysis.findMany({
      where: { profileId },
      orderBy: { createdAt: "desc" },
      take: limit,
    });
  }

  /** Records the outcome and usage of an OpenAI request. */
  static async createRequest(data: Prisma.AIRequestUncheckedCreateInput): Promise<void> {
    await prisma.aIRequest.create({ data });
  }
}
